version: '3.4'
services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=admin'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
    ports:
      - '37017:27017'
    volumes:
      - ./data/mongo/users.js:/docker-entrypoint-initdb.d/users.js:ro

  abntechdmeo-app:
    depends_on:
      - mongodb
    build: .
    image: abntestproject:latest
    environment:
      - 'SPRING_DATA_MONGODB_URI=mongodb://adminuser:pAssw0rd@host.docker.internal:37017/?authSource=admin&authMechanism=SCRAM-SHA-256'
      - 'SPRING_DATA_MONGODB_DATABASE=demodb'
      - 'JWT_SECRET=qPfgaTEWEP3S9w0tgsicURfo-nLW09_0KfOPinhYZ4ouzU-3xC4pSlEp8Ut9FgL0AgqNslNaK34Kq-NZjO9DAQ=='
    ports:
      - '8080:8080'
volumes:
  data: